### PR TITLE
MWPW-162614: Normalize UX for field updates

### PR DESCRIPTION
**Pull request by yesil**
Refactored the editor panel in own custom element
added unit tests.

Resolve: 
* https://jira.corp.adobe.com/browse/MWPW-162614
* https://jira.corp.adobe.com/browse/MWPW-161187

Test URLs:
- Before: https://main--mas--adobecom.hlx.page/studio.html
- After: https://mwpw-162614--mas--adobecom.hlx.page/studio.html

### CODE REVIEW

**Review by npeltier — APPROVED** [review]

**Review by 3ch023 — APPROVED** [review]

**Comment by afmicka** [comment]
@yesil when you make a change to any of the fields, it does get rendered immediately in the preview but the status dot stays green (even if you move focus from the field), does not indicate any of the changes (should turn into yellow after any change and blue when saved but not yet published) . 
Screenshot 2024-11-28 at 12 50 58

**Comment by afmicka** [comment]
@yesil Also, changes in the links in description RTE are not rendered in the preview (not before and not after the form save). 
Screenshot 2024-11-28 at 13 58 17

**Comment by afmicka** [comment]
Those changes are not validated. It made it worse now for the link editing. It does not render at all the changes in the RTE. Earlier at least it worked if the link already exist in the field
Screenshot 2024-11-28 at 15 29 56

**Comment by afmicka** [comment]
Looks good to me

**Comment by afmicka** [comment]
@yesil I have removed the verified label. I checked the studio with your CSS switch branch and it is breaking the view. On hover cards are pitch black

https://mwpw-162614--mas--adobecom.hlx.page/studio.html?milolibs=MWPW-163479--milo--adobecom#path=nala
Screenshot 2024-12-11 at 10 41 28

**Pull request merged**
