### PR TITLE
MWPW-159269 add size field

### PR DESCRIPTION
**Pull request by npeltier**
Test URLs:
- Before: https://main--mas--adobecom.hlx.live/
- After: https://MWPW-159269--mas--adobecom.hlx.live/

### CODE REVIEW

**Review by Axelcureno — APPROVED** [review]

**Review by 3ch023 — COMMENTED** [review]
Do we need to add details of how to specify the size?
e.g. S/L/M or small/large or pixels

also, another thought, we could put the 'Optional' into the name field to make it more explicit to GWP what fields are not necessary, wdyt?

**Review by 3ch023 — APPROVED** [review]

**Comment by npeltier** [comment]
> also, another thought, we could put the 'Optional' into the name field to make it more explicit to GWP what fields are not necessary, wdyt?

i think that we have not dealt with the variant -> fields mapping in authoring yet (even if we did it for hydration), and at that moment yes, we could foresee such things (even check box for slice card "is wide ?"). It makes even more sense not having size field at all for lot of variants

**Comment by 3ch023** [comment]
> > also, another thought, we could put the 'Optional' into the name field to make it more explicit to GWP what fields are not necessary, wdyt?
> 
> i think that we have not dealt with the variant -> fields mapping in authoring yet (even if we did it for hydration), and at that moment yes, we could foresee such things (even check box for slice card "is wide ?"). It makes even more sense not having size field at all for lot of variants

We could add it later, true.
So what are the possible values for the size field?

**Comment by npeltier** [comment]
> So what are the possible values for the size field

**Pull request merged**
